# A web service that builds from a Dockerfile
  - type: web
    runtime: docker
    name: report-site
    startCommand: >
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn reportsite.wsgi:application --bind 0.0.0.0:$PORT