# Generated by Django 5.1.5 on 2025-04-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='daily_input_token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daily_output_token_count',
            field=models.IntegerField(default=0),
        ),
    ]
