# Generated by Django 5.1.5 on 2025-10-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tokenusage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
